# Generated by Django 2.1 on 2019-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('age', models.IntegerField(default=10, null=True)),
                ('employee_id', models.IntegerField(max_length=20, null=True)),
            ],
        ),
    ]
